### ISSUE TITLE
Use radio.onReceivedValue instead of onDataPacketReceived

### ISSUE THREAD

**Issue by pelikhan** [CaptainCredible/pxt-microBitOrchestra#9]
https://github.com/CaptainCredible/pxt-microBitOrchestra/blob/be2a8bdcad48efd2c5b3dcbf35107eb170c262e7/orchestraInstrument.ts#L177

This function is deprecated in v2, try replace it with ``radio.onReceivedValue``.

**Comment by CaptainCredible** [comment]
Done
